server:
  port: 8080
spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/disertatie?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    url: jdbc:mysql://localhost:3306/disertatie?serverTimezone=UTC
    username: root
    password:
ssh:
  port: 22
  host: 10.21.80.6
  user: sysop-rognss
  password: sysop-rognss
  path: gps_dbase/